version: '3'

services:
  wordpress_db:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - wordpress_db_data:/var/lib/mysql
      - .docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootwordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress_app:
    depends_on:
      - wordpress_db
    build: .docker/wordpress
    volumes:
      - ./src/themes:/var/www/html/wp-content/themes
      - ./src/uploads:/var/www/html/wp-content/uploads
      - ./src/plugins:/var/www/html/wp-content/plugins
      - ./src/wp-config.php:/var/www/html/wp-config.php
      - .docker/wordpress/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - 8000:80
    # restart: always
    # environment:
    #   WORDPRESS_DB_HOST: wordpress_db:3306
    #   WORDPRESS_DB_USER: wordpress
    #   WORDPRESS_DB_PASSWORD: wordpress
volumes:
  wordpress_db_data:
